# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 355e410cdd577a17c4ca5fec202ec86c45be1bb0a30d63d1397631fc6f3d50c7ec5bd06a45edf80de5d9e61da92f15f16eb002df270d157f130393380bfdce0c

test:
  secret_key_base: fe74b6f3841e62ea80b73d39c9c3e7c1cf7ab51c90e9522bf42bcd954224468357e9b47265ece2da4b5bc56158a7cfae9a2e7b3f6ef90eaef6ce2ec96f0413c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
